site_name: FastAPI CRUD Router Mongodb
site_url: https://pierrod.github.io/fastapi-crudrouter-mongodb-doc/
site_author: Pierre Duveau
site_description:
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/img/logo-white.png
  favicon: assets/img/logo-color.png
  language: en
repo_name: pierrod/fastapi-crudrouter-mongodb
repo_url: https://github.com/pierrod/fastapi-crudrouter-mongodb
edit_uri: ""
nav:
  - Home: index.md
  - QuickStart: 
    - quickstart/index.md
    - quickstart/01-installation-setup.md
    - quickstart/02-models-and-schemas.md
    - quickstart/03-crud-operations.md
    - quickstart/04-filtering-sorting-pagination.md
    - quickstart/05-related-data.md
    - quickstart/06-advanced-patterns.md
    - quickstart/07-production-ready.md
  - Reference:
    - Routing: reference/routing.md
    - Models: 
      - reference/models/MongoModel.md
      - reference/models/MongoObjectId.md
      - reference/models/DeletedModelOut.md
      - reference/models/ models-and-schemas.md
    - APIs and Router:
      - reference/apis/CRUDRouter.md
      - reference/apis/CRUDLookup.md
      - reference/apis/CRUDEmbed.md
      - reference/apis/CRUDPopulate.md
    - Services:
      - reference/services/CRUDService.md
    - Repositories:
      - reference/repositories/CRUDRepository.md

  - Examples:
      - examples/minimalist.md
      - examples/basic-crud.md
      - examples/relationships.md
      - examples/service-and-repository.md
      
  - Migrate Pydantic from v1 to v2: migrate.md
  - Releases notes: releases.md

markdown_extensions:
  - toc:
      permalink: true
  - extra
  - admonition
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pierrod/fastapi-crudrouter-mongodb
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pierre-duveau-193586182
    - icon: fontawesome/solid/globe
      link: https://github.com/pierrod
  version:
    provider: mike
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
